FROM python:3.8-slim-buster

WORKDIR /app

COPY ./requirements.txt requirements.txt

RUN pip install -r requirements.txt

ENV ROOT_PATH /test

COPY . .

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]